---
- name: test if lynis_destination is set correctly
  assert:
    that:
      - lynis_destination is defined
    quiet: yes

- name: test if lynis_version is set correctly
  assert:
    that:
      - lynis_version is defined
    quiet: yes

- name: test if lynis_output is set correctly
  assert:
    that:
      - lynis_output is defined
    quiet: yes

- name: test if lynis_run_now is set correctly
  assert:
    that:
      - lynis_run_now is defined
      - lynis_run_now is boolean
    quiet: yes

- name: test if lynis_cronjob is set correctly
  assert:
    that:
      - lynis_cronjob is defined
      - lynis_cronjob is boolean
    quiet: yes
