---
- name: test if lynis_destination is set correctly
  assert:
    that:
      - lynis_destination is defined
      - lynis_destination | length > 0

- name: test if lynis_version is set correctly
  assert:
    that:
      - lynis_version is defined
      - lynis_version | length > 0

- name: test if lynis_output is set correctly
  assert:
    that:
      - lynis_output is defined
      - lynis_output | length > 0

- name: test if lynis_run_now is set correctly
  assert:
    that:
      - lynis_run_now is defined
      - lynis_run_now | type_debug == "bool"

- name: test if lynis_cronjob is set correctly
  assert:
    that:
      - lynis_cronjob is defined
      - lynis_cronjob | type_debug == "bool"
